database:
  db_name: "postgres"
  driver: "postgres"
  host: "localhost"
  is_test: false
  password: "secret"
  port: 5432
  user: "root"
grpc:
  cert: "./workspace/ssl/server.crt"
  client: "localhost:9092"
  key: "./workspace/ssl/server.pem"
  protocol: "tcp"
  server: "localhost:9091"
rabbitmq:
  exchange:
    durable: true
    name: "exchange.go.tutorials"
    type: "topic"
  host: "chimpanzee.rmq.cloudamqp.com"
  password: "F6-m21vrQokbdCys_upLFsH2X2kfxl2J"
  port: 5671
  protocol: "amqps"
  queue:
    durable: true
    message_ttl: 60000
    name: "QU-APP-GRPC-EMAIL-MICROSERVICE"
    type: "quorum"
  routing_key:
    request: "service.app.go.transaction.request"
    response: "service.*.go.tutorials.transaction.response"
  tls_enable: true
  user: "kjsycjee"
  vhost: "kjsycjee"
scheduler:
  enable: true
server:
  environment: "prod"
  host: "localhost"
  logging: "debug"
  logs: "/home/christian/workspace/go/src/logs"
  name: "go"
  port: 3000
  timeout: 30
ssh:
  enable: false
  host: "localhost"
  known_hosts: "pkg/adapters/ssh/workspace/docker/keys/known_hosts"
  password: "cbaciliod"
  port: 2222
  private_key: "pkg/adapters/ssh/workspace/docker/keys/id_rsa"
  protocol: tcp
  public_key: "pkg/adapters/ssh/workspace/docker/keys/id_rsa.pub"
  sftp_path: "local"
  username: "cbaciliod"